spring.application.name=mini06

# data source
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/jpa_fitness
spring.datasource.username=ureca
spring.datasource.password=ureca

# session persistence
server.servlet.session.persistent=false

# jpa
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# junit test logging
logging.level.root=INFO
logging.level.com.mycom.myapp=DEBUG

#jwt secret key
jwt.secret=nsdhjf2euqnbhfio2qnfoiwen0gqnsdvjq2j9ifr023
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000