spring.application.name=mini06

# data source
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/fitness_reserve
spring.datasource.username=
spring.datasource.password=

# session persistence
server.servlet.session.persistent=false

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=
jwt.access-token-expiration=30m
jwt.refresh-token-expiration=14d